# Configured for ESLint 3.4.0
root: true

extends: eslint:recommended
rules:

  # Best Practices
  accessor-pairs: 2
  array-callback-return: 2
  block-scoped-var: 2
  consistent-return: 2
  curly: 2
  dot-location: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-div-regex: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-global-assign: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-new: 2
  no-octal-escape: 2
  no-process-env: 2
  no-proto: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unexpected-multiline: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-concat: 2
  no-void: 2
  no-warning-comments: 1
  no-with: 2
  radix: 2
  wrap-iife: 2

  # Strict Mode
  strict: 2

  # Variables
  no-catch-shadow: 2
  no-label-var: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-undef-init: 2
  no-use-before-define: 2

  # Node.js and CommonJS
  callback-return: 2
  global-require: 2
  handle-callback-err: 2
  no-new-require: 2
  no-path-concat: 2
  no-process-exit: 2
  no-sync: 2

  # Stylistic Issues
  array-bracket-spacing: 2
  block-spacing: 2
  brace-style: 2
  camelcase: 2
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  eol-last: 2
  func-call-spacing: 2
  func-style: 2
  indent:
    - 2
    - 2
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style: 2
  new-cap: 2
  new-parens: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-continue: 2
  no-multiple-empty-lines: 2
  no-negated-condition: 2
  no-new-object: 2
  no-plusplus: 2
  no-trailing-spaces: 2
  no-whitespace-before-property: 2
  object-curly-spacing: 2
  one-var-declaration-per-line: 2
  operator-linebreak:
    - 2
    - after
  quotes:
    - 2
    - single
  semi: 2
  semi-spacing: 2
  space-before-blocks: 2
  space-before-function-paren: 2
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: 2
  wrap-regex: 2
